# Generated by Django 4.0.4 on 2022-05-19 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweep',
            name='tags',
        ),
        migrations.AlterField(
            model_name='tweep',
            name='tweeps',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tweep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
